/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:493474:
  appc.background(230);
} //_CODE_:window1:493474:

public void nextCard(GButton source, GEvent event) { //_CODE_:nextButton:541649:
  if(displayed.displayed + 1 < displayed.qtCards) {
  displayed.displayedCard.Front = true;
  displayed.displayed += 1;
  displayed.switchCard(displayed.displayed);}
  else {println("you're at the end of the deck!");}
} //_CODE_:nextButton:541649:

public void flipCard(GButton source, GEvent event) { //_CODE_:flipButton:427618:
  displayed.displayedCard.Front = !displayed.displayedCard.Front;
} //_CODE_:flipButton:427618:

public void prevCard(GButton source, GEvent event) { //_CODE_:prevButton:615710:
  if(displayed.displayed - 1 >= 0) {
  displayed.displayedCard.Front = true;
  displayed.displayed -= 1;
  displayed.switchCard(test.displayed);}
  else {println("you're at the beginning of the deck!");}
} //_CODE_:prevButton:615710:

public void starCard(GButton source, GEvent event) { //_CODE_:starButton:421702:
  displayed.displayedCard.Star = !displayed.displayedCard.Star;
} //_CODE_:starButton:421702:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:deckname:506753:
} //_CODE_:deckname:506753:

public void submitname(GButton source, GEvent event) { //_CODE_:submitbutton:260575:
  String temp = deckname.getText();
  loadDeck(temp);
  if(temp == null) {println("this deck does not exist! did you enter the name correctly?");}
} //_CODE_:submitbutton:260575:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Controls", 0, 0, 300, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  nextButton = new GButton(window1, 100, 10, 80, 30);
  nextButton.setText("Next Card");
  nextButton.addEventHandler(this, "nextCard");
  flipButton = new GButton(window1, 10, 50, 80, 30);
  flipButton.setText("Flip Card");
  flipButton.addEventHandler(this, "flipCard");
  prevButton = new GButton(window1, 10, 10, 80, 30);
  prevButton.setText("Last Card");
  prevButton.addEventHandler(this, "prevCard");
  starButton = new GButton(window1, 10, 135, 80, 30);
  starButton.setText("Star");
  starButton.addEventHandler(this, "starCard");
  deckname = new GTextField(window1, 76, 253, 120, 30, G4P.SCROLLBARS_NONE);
  deckname.setOpaque(true);
  deckname.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(window1, -3, 251, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Load deck:");
  label1.setOpaque(false);
  submitbutton = new GButton(window1, 205, 251, 80, 30);
  submitbutton.setText("Enter");
  submitbutton.addEventHandler(this, "submitname");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton nextButton; 
GButton flipButton; 
GButton prevButton; 
GButton starButton; 
GTextField deckname; 
GLabel label1; 
GButton submitbutton; 
