/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void handleBtnA(GButton source, GEvent event) { 
  if (activeQuiz != null && !activeQuiz.isFinished) activeQuiz.checkAnswer(0); 
}

public void handleBtnB(GButton source, GEvent event) { 
  if (activeQuiz != null && !activeQuiz.isFinished) activeQuiz.checkAnswer(1); 
}

public void handleBtnC(GButton source, GEvent event) { 
  if (activeQuiz != null && !activeQuiz.isFinished) activeQuiz.checkAnswer(2); 
}

public void handleBtnD(GButton source, GEvent event) { 
  if (activeQuiz != null && !activeQuiz.isFinished) activeQuiz.checkAnswer(3); 
}



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  btnA = new GButton(this, 58, 74, 80, 30);
  btnA.setText("A");
  btnA.addEventHandler(this, "handleBtnA");
  btnB = new GButton(this, 194, 73, 80, 30);
  btnB.setText("B");
  btnB.addEventHandler(this, "handleBtnB");
  btnC = new GButton(this, 57, 122, 80, 30);
  btnC.setText("C");
  btnC.addEventHandler(this, "handleBtnC");
  btnD = new GButton(this, 193, 122, 80, 30);
  btnD.setText("D");
  btnD.addEventHandler(this, "handleBtnD");
}

// Variable declarations 
// autogenerated do not edit
GButton btnA; 
GButton btnB; 
GButton btnC; 
GButton btnD; 
