/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void TextAnswer(GTextArea source, GEvent event) { //_CODE_:AnswerText:686908:
} //_CODE_:AnswerText:686908:

public void TextQuestion(GTextArea source, GEvent event) { //_CODE_:QuestionText:934927:
  
} //_CODE_:QuestionText:934927:

public void New(GButton source, GEvent event) { //_CODE_:NewCard:611985:
 String[] temp = new String[2];
 deckContent.add(temp);
} //_CODE_:NewCard:611985:

public void ExportDeck(GButton source, GEvent event) { //_CODE_:Export:759024:
  exporter = createWriter("data/"+ Title + ".txt");
  
  exporter.println("D");
  
  for(int i = 0; i < deckContent.size(); i++) {
    exporter.println(deckContent.get(i)[0]);
    exporter.println(deckContent.get(i)[1]); 
  }
  
  exporter.flush();
  exporter.close();
  resetProgram();
} //_CODE_:Export:759024:

public void PreviousCard(GButton source, GEvent event) { //_CODE_:PrevButton:238548:
  if(currCard > 0) {
    currCard --;
    resetText();
  }
} //_CODE_:PrevButton:238548:

public void NextCard(GButton source, GEvent event) { //_CODE_:NextButton:605521:
  if(currCard < deckContent.size() - 1) {
    currCard ++;
    resetText();
  }
} //_CODE_:NextButton:605521:

public void DeleteCard(GButton source, GEvent event) { //_CODE_:DeleteButton:972669:
  if(deckContent.size() > 1) {
  deckContent.remove(deckContent.get(currCard));
  
  if(currCard == deckContent.size()) {
  currCard --;}
  }
  
  else {
  deckContent.get(0)[0] = "";
  deckContent.get(0)[1] = "";
  }
  
 resetText();
  
} //_CODE_:DeleteButton:972669:

public void UpdateCard(GButton source, GEvent event) { //_CODE_:UpdateButton:334758:
  deckContent.get(currCard)[0] = QuestionText.getText();
  deckContent.get(currCard)[1] = AnswerText.getText();
  print(deckContent.get(currCard));
} //_CODE_:UpdateButton:334758:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:NewDeckMenu:766128:
  appc.background(230);
} //_CODE_:NewDeckMenu:766128:

public void NameEntry(GTextField source, GEvent event) { //_CODE_:DeckName:717840:
} //_CODE_:DeckName:717840:

public void NameSubmit(GButton source, GEvent event) { //_CODE_:SubmitName:951850:
  Title = DeckName.getText();
  deckContent = new ArrayList();
  String[] temp = new String[2];
  deckContent.add(temp);
  currCard = 0;
  NewDeckMenu.setVisible(false);
  AnswerText.setVisible(true);
  QuestionText.setVisible(true);
  NewCard.setVisible(true);
  Export.setVisible(true);
  PrevButton.setVisible(true);
  NextButton.setVisible(true);
  DeleteButton.setVisible(true);
  UpdateButton.setVisible(true);
} //_CODE_:SubmitName:951850:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  AnswerText = new GTextArea(this, 200, 200, 200, 130, G4P.SCROLLBARS_NONE);
  AnswerText.setPromptText("Answer Text Here");
  AnswerText.setOpaque(true);
  AnswerText.addEventHandler(this, "TextAnswer");
  QuestionText = new GTextArea(this, 200, 20, 200, 130, G4P.SCROLLBARS_NONE);
  QuestionText.setPromptText("Question Text Here");
  QuestionText.setOpaque(true);
  QuestionText.addEventHandler(this, "TextQuestion");
  NewCard = new GButton(this, 10, 50, 80, 30);
  NewCard.setText("New Card");
  NewCard.addEventHandler(this, "New");
  Export = new GButton(this, 10, 300, 170, 30);
  Export.setText("Finish and Export");
  Export.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  Export.addEventHandler(this, "ExportDeck");
  PrevButton = new GButton(this, 10, 120, 80, 30);
  PrevButton.setText("Previous");
  PrevButton.addEventHandler(this, "PreviousCard");
  NextButton = new GButton(this, 100, 120, 80, 30);
  NextButton.setText("Next");
  NextButton.addEventHandler(this, "NextCard");
  DeleteButton = new GButton(this, 100, 50, 80, 30);
  DeleteButton.setText("Delete Card");
  DeleteButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  DeleteButton.addEventHandler(this, "DeleteCard");
  UpdateButton = new GButton(this, 10, 10, 170, 30);
  UpdateButton.setText("Update Card");
  UpdateButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  UpdateButton.addEventHandler(this, "UpdateCard");
  NewDeckMenu = GWindow.getWindow(this, "New Deck", 0, 0, 300, 120, JAVA2D);
  NewDeckMenu.noLoop();
  NewDeckMenu.setActionOnClose(G4P.KEEP_OPEN);
  NewDeckMenu.addDrawHandler(this, "win_draw1");
  label2 = new GLabel(NewDeckMenu, 10, 10, 150, 20);
  label2.setTextAlign(GAlign.LEFT, GAlign.BOTTOM);
  label2.setText("CREATE NEW DECK");
  label2.setOpaque(false);
  DeckName = new GTextField(NewDeckMenu, 10, 30, 120, 30, G4P.SCROLLBARS_NONE);
  DeckName.setText("Enter Deck Name");
  DeckName.setPromptText("Enter Deck Name");
  DeckName.setOpaque(true);
  DeckName.addEventHandler(this, "NameEntry");
  SubmitName = new GButton(NewDeckMenu, 10, 80, 80, 30);
  SubmitName.setText("Submit");
  SubmitName.addEventHandler(this, "NameSubmit");
  NewDeckMenu.loop();
}

// Variable declarations 
// autogenerated do not edit
GTextArea AnswerText; 
GTextArea QuestionText; 
GButton NewCard; 
GButton Export; 
GButton PrevButton; 
GButton NextButton; 
GButton DeleteButton; 
GButton UpdateButton; 
GWindow NewDeckMenu;
GLabel label2; 
GTextField DeckName; 
GButton SubmitName; 
